### ISSUE TITLE
Memory orderings in futex based manual_reset_event

### ISSUE THREAD

**Issue by fxkaiser** [boostorg/sync#16]
Hey guys, 

can someone explain to me the selection of memory_orders in the futex based manual_reset_event implementation ? Why is only the final store in wait()/timed_wait() an acquire operation and why is the store in reset() relaxed ? As far as I understand the store in post() synchronizes with the final load in wait() / timed_wait() but this makes (to my understanding) only all modifications that happened before the store in post visible to the load in wait()/timed_wait() but there they are not used. The store in wait()/timed_wait() might drop the wait_count to zero which should be visible after the store in set() since the wait_count is checked before the call to futex_broadcast. Why are these memory orderings sufficient ?

Best regards,
fxkaiser

**Comment by Lastique** [comment]
`set` and `wait` have to have release and acquire semantics, respectively, in order that the notifying thread *synchronizes-with* the waiting thread. Put simply, the waiting thread that has woken up in `wait` has to observe memory modifications that were made by the notifying thread before it called `set`. This includes any user's data besides the event object itself. User's data is the main reason why the memory order is enforced to anything but relaxed.

`reset` does not *synchronize-with* other threads, so it can have relaxed semantics.
